-- MySQL Script generated by MySQL Workbench
-- Wed Oct 26 16:14:14 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persons` (
  `person_id` INT NOT NULL AUTO_INCREMENT COMMENT 'AI=100',
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` INT(10) NULL,
  `username` VARCHAR(45) NULL,
  `passwd` VARCHAR(45) NULL,
  `created_by` INT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_by` INT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 100;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT COMMENT 'AI=10',
  `role_name` VARCHAR(45) NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10;


-- -----------------------------------------------------
-- Table `mydb`.`acl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`acl` (
  `person_id` INT NULL,
  `role_id` INT NULL,
  INDEX `fk_p_id_idx` (`person_id` ASC),
  INDEX `fk_r_id_idx` (`role_id` ASC),
  CONSTRAINT `fk_p_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`persons` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_r_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instructor_enrollment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instructor_enrollment` (
  `inst_id` INT NOT NULL,
  `student_id` INT NULL,
  `start_date` DATE NULL,
  `created_by` INT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_by` INT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`inst_id`),
  INDEX `fk_student_id_idx` (`student_id` ASC),
  CONSTRAINT `fk_inst_id`
    FOREIGN KEY (`inst_id`)
    REFERENCES `mydb`.`persons` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`persons` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instructor_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instructor_time` (
  `ins_time_id` INT NOT NULL AUTO_INCREMENT COMMENT 'ai-1000',
  `inst_id` INT NULL,
  `student_id` INT NULL,
  `date` DATE NULL,
  `hours` TIME NULL,
  `status` VARCHAR(45) NULL,
  `created_by` INT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_by` INT NULL,
  `updated_at` VARCHAR(45) NULL,
  PRIMARY KEY (`ins_time_id`),
  INDEX `fk_inst_id_idx` (`inst_id` ASC),
  INDEX `fk_student_id_idx` (`student_id` ASC),
  CONSTRAINT `fk_inst_id`
    FOREIGN KEY (`inst_id`)
    REFERENCES `mydb`.`persons` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`persons` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1000;


-- -----------------------------------------------------
-- Table `mydb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`status` (
  `status_id` INT NOT NULL AUTO_INCREMENT COMMENT 'AI=0',
  `status_name` VARCHAR(45) NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0;


-- -----------------------------------------------------
-- Table `mydb`.`inst_time_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inst_time_status` (
  `inst_time_id` INT NULL,
  `status_id` INT NULL,
  INDEX `fk_inst_t_id_idx` (`inst_time_id` ASC),
  INDEX `fk_status_id_idx` (`status_id` ASC),
  CONSTRAINT `fk_inst_t_id`
    FOREIGN KEY (`inst_time_id`)
    REFERENCES `mydb`.`instructor_time` (`ins_time_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_status_id`
    FOREIGN KEY (`status_id`)
    REFERENCES `mydb`.`status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
